name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Infrastructure and Lambda
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws sts get-caller-identity

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3

      # Step 4: Initialize Terraform Backend
      - name: Initialize Terraform Backend
        working-directory: terraform/backend
        run: terraform init -reconfigure

      # Step 5: Plan Terraform Backend Resources
      - name: Plan Backend Resources
        working-directory: terraform/backend
        run: terraform plan -out=backend.tfplan

      # Step 6: Apply Terraform Backend Resources
      - name: Apply Backend Resources
        working-directory: terraform/backend
        run: terraform apply backend.tfplan

      # Step 7: Initialize Terraform Infrastructure
      - name: Initialize Terraform Infrastructure
        working-directory: terraform/infrastructure
        run: terraform init -reconfigure

      # Step 8: Plan Terraform Infrastructure Resources
      - name: Plan Infrastructure Resources
        working-directory: terraform/infrastructure
        run: terraform plan -out=infrastructure.tfplan

      # Step 9: Apply Terraform Infrastructure Resources
      - name: Apply Infrastructure Resources
        working-directory: terraform/infrastructure
        run: terraform apply infrastructure.tfplan

      # Step 10: Package Lambda Function
      - name: Package Lambda Function
        run: zip lambda_function.zip lambda_function.py

      # Step 11: Deploy Lambda Function
      - name: Deploy Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name merge-homeless-data \
            --zip-file fileb://lambda_function.zip

      # Step 12: Upload Dataset Files to S3
      - name: Upload Dataset Files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp files/SF_HOMELESS_ANXIETY.csv s3://friday-ugbebor-datasets/raw/SF_HOMELESS_ANXIETY.csv
          aws s3 cp files/SF_HOMELESS_DEMOGRAPHICS.csv s3://friday-ugbebor-datasets/raw/SF_HOMELESS_DEMOGRAPHICS.csv
