name: Deploy Infrastructure and Lambda

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Backend Deployment
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws sts get-caller-identity

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3

      - name: Initialize Terraform Backend
        working-directory: terraform/backend
        run: terraform init -reconfigure

      - name: Plan Backend Resources
        working-directory: terraform/backend
        run: terraform plan -out=backend.tfplan

      - name: Apply Backend Resources
        working-directory: terraform/backend
        run: terraform apply backend.tfplan

  # Job 2: Infrastructure and Lambda Deployment
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws sts get-caller-identity

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3

      - name: Initialize Terraform for Infrastructure
        working-directory: terraform/infrastructure
        run: terraform init -reconfigure

      - name: Plan Infrastructure Resources
        working-directory: terraform/infrastructure
        run: terraform plan -out=infra.tfplan

      - name: Apply Infrastructure Resources
        working-directory: terraform/infrastructure
        run: terraform apply infra.tfplan

      - name: Package Lambda Function
        run: |
          zip lambda_function.zip lambda_function.py

      - name: Deploy Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lambda update-function-code \
            --function-name merge-homeless-data \
            --zip-file fileb://lambda_function.zip

      - name: Upload Files to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp files/SF_HOMELESS_ANXIETY.csv s3://friday-ugbebor-datasets/raw/SF_HOMELESS_ANXIETY.csv
          aws s3 cp files/SF_HOMELESS_DEMOGRAPHICS.csv s3://friday-ugbebor-datasets/raw/SF_HOMELESS_DEMOGRAPHICS.csv


          
# name: Deploy Infrastructure

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: Deploy Infrastructure and Lambda
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Configure AWS Credentials
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: ${{ secrets.AWS_REGION }}
#         run: aws sts get-caller-identity

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.5.3

#       - name: Initialize Terraform Backend
#         working-directory: terraform/backend
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: ${{ secrets.AWS_REGION }}
#         run: terraform init -reconfigure

#       - name: Plan Backend Resources
#         working-directory: terraform/backend
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: ${{ secrets.AWS_REGION }}
#         run: terraform plan -out=backend.tfplan

#       - name: Apply Backend Resources
#         working-directory: terraform/backend
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: ${{ secrets.AWS_REGION }}
#         run: terraform apply backend.tfplan
